### PR TITLE
Add fun getSprites

### PR DESCRIPTION
**Pull request by giaba90**
Get URI of image of Pokemon

### CODE REVIEW

**Comment by adithyaMohan200** [comment]
Oh yeah, I forgot about Sprites. Thanks for the reminder. One thing though. Instead of returning the front default, it's simpler to just   return self.info['sprites']  . This returns a dictionary with links for all views

**Comment by adithyaMohan200** [comment]
I"ll merge this though, and just change that

**Comment by giaba90** [comment]
Sorry man. But my preferite sprite is "front default". With this in mind, i wrote the code. Sorry ! 
Thanks for the "merge"

**Comment by adithyaMohan200** [comment]
Oh no problem, thanks for the reminder!

**Pull request merged**
